import React from "react";
import Head from "next/head";
import StorySection from "../components/About/StorySection";
import JourneySection from "../components/About/JourneySection";
import CTASection from "../components/Home/CTASection";
import FAQSection from "../components/About/FAQSection";

const AboutPage = ({ openCalendly }) => {
  return (
    <>
      <Head>
        <title>{"Web3 React Developer - About Me"}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <StorySection />
      <JourneySection />
      <FAQSection />
      <CTASection openCalendly={openCalendly} />
    </>
  );
};

export default AboutPage;
