import React from "react";
import Head from "next/head";
import StorySection from "../components/About/StorySection";
import JourneySection from "../components/About/JourneySection";

const AboutPage = ({ openCalendly }) => {
  return (
    <>
      <Head>
        <title>{"Web3 React Developer - yewyewXD"}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <StorySection />
      <JourneySection />
    </>
  );
};

export default AboutPage;
