import Head from "next/head";
import AppHeader from "../components/AppHeader";
import ValueSection from "../components/Home/ValueSection";
import HeroSection from "../components/Home/HeroSection";
import ReviewSection from "../components/Home/ReviewSection";
import ProjectSection from "../components/Home/ProjectSection";
import CTASection from "../components/Home/CTASection";
import AppFooter from "../components/AppFooter";

const Home = () => {
  return (
    <div>
      <Head>
        <title>{"Web3 React Developer - yewyewXD"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppHeader />

      <main>
        <HeroSection />
        <ValueSection />
        <ReviewSection />
        <ProjectSection />
        <CTASection />
      </main>

      <AppFooter />
    </div>
  );
};

export default Home;
