import Head from "next/head";
import HeroSection from "../components/Home/HeroSection";

const Home = () => {
  return (
    <div>
      <Head>
        <title>{"yewyewXD | Yew's Portfolio"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <HeroSection />
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
